gText_Birch_Welcome:: @ 82C897B
.string "Hey... Hey!\p"
.string "You're awake!\p"
.string "You were out for quite some time,\n"
.string "my friend. Wow!\n"
.string "...\p"
.string "$"

gText_Birch_Pokemon:: @ 82C89FB


gText_Birch_MainSpeech:: @ 82C8A1F
.string "You: Ugh... Agh...\p"
.string "...Where... Where am I?\p"
.string "Man: Now he's awake...\p"
.string "Just lie back down, kid, relax...\p"
.string "You: ...\p"
.string "What... what happened...\n"
.string "...Agh! Christ, my head!\p"
.string "Man: Whoa, take it easy...\n"
.string "Want a glass of water?\p"
.string "You: No... I'm good...\p"
.string "Man: Alright then. Don't worry,\n"
.string "you're in good hands. Relax.\p"
.string "You're gonna be OK.\p"
.string "You: Who... who are you?\p"
.string "Man: I might ask you the same.\p"
.string "Can you tell me your name?\p"
.string "You: Name?.... Uhh...\p"
.string "Man: What, you don't remember?\p"
.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0


gText_Birch_BoyOrGirl:: @ 82C8BDD


gText_Birch_WhatsYourName:: @ 82C8BFF
.string "What's your name, kid?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
.string "I see... you're {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
.string "Good.\n"
.string "At least you remember that much.\p"
.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
.string "You: But... how did I...\p"
.string "Man: Lie back down. The doctor will\n"
.string "be here in a minute. Get some rest.\p"
.string "You: My fucking head...\p"
.string "Man: It's OK. Here he is.\n"
.string "Here's the doctor.\p"
.string "Just relax.\p"
.string "Wait for the morphine to kick in...\p"
.string "$"
