OldaleTown_House2_EventObjects::
	object_event 1, EVENT_OBJ_GFX_GIRL_2, 0, 2, 2, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, OldaleTown_House2_EventScript_Receptionist, 0

OldaleTown_House2_MapWarps::
	warp_def 7, 7, 0, 1, MAP_OLDALE_TOWN
	warp_def 8, 7, 0, 1, MAP_OLDALE_TOWN
	warp_def 9, 1, 3, 0, MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR

OldaleTown_House2_MapEvents::
	map_events OldaleTown_House2_EventObjects, OldaleTown_House2_MapWarps, 0x0, 0x0
