LilycoveCity_DepartmentStoreElevator_EventObjects::
	object_event 1, EVENT_OBJ_GFX_MAN_4, 0, 4, 3, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, LilycoveCity_DepartmentStoreElevator_EventScript_Man, 0

LilycoveCity_DepartmentStoreElevator_MapWarps::
	warp_def 1, 5, 3, 2, MAP_OLDALE_TOWN_HOUSE2
	warp_def 2, 5, 3, 2, MAP_OLDALE_TOWN_HOUSE2

LilycoveCity_DepartmentStoreElevator_MapEvents::
	map_events LilycoveCity_DepartmentStoreElevator_EventObjects, LilycoveCity_DepartmentStoreElevator_MapWarps, 0x0, 0x0
