LittlerootTown_BrendansHouse_1F_EventObjects::
	object_event 1, EVENT_OBJ_GFX_MAN_5, 0, 4, 6, 3, MOVEMENT_TYPE_FACE_LEFT, 0, 0, FALSE, 0, LittlerootTown_BrendansHouse_1F_EventScript_Guy, 0

LittlerootTown_BrendansHouse_1F_MapWarps::
	warp_def 9, 8, 0, 0, MAP_LITTLEROOT_TOWN
	warp_def 8, 8, 0, 0, MAP_LITTLEROOT_TOWN
	warp_def 9, 1, 0, 0, MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F

LittlerootTown_BrendansHouse_1F_MapEvents::
	map_events LittlerootTown_BrendansHouse_1F_EventObjects, LittlerootTown_BrendansHouse_1F_MapWarps, 0x0, 0x0
